<a href="https://www.kaggle.com/code/matinmahmoudi/numpy-fun-problems-intermediate?scriptVersionId=166681596" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# My Solutions for Numpy Fun Problems - Intermediate

In this notebook, I am tackling the "Intermediate" level practice problems, which you can find at the following source:

- [Practice Problems Source](https://www.practiceprobs.com/problemsets/python-numpy/intermediate/)

For additional learning and insights, I also recommend watching related content on YouTube. One particularly helpful resource I've found is:

- [YouTube Tutorial](https://www.youtube.com/watch?v=eClQWW_gbFk)

If you're progressing through these problem sets and looking to advance further, consider moving on to the next level of challenges. I have also provided solutions for the "Proficient" level, available here:

- [Next Notebook: Numpy Fun Problems - Proficient](https://www.kaggle.com/code/matinmahmoodi/numpy-fun-problems-proficient)

Your feedback and alternative solutions are highly appreciated, as they foster learning and improvement. Please feel free to share your thoughts in the comments section.

### **If this notebook aids your learning, kindly support it with an upvote!**


# Q1 - Love Distance Problem

https://www.practiceprobs.com/problemsets/python-numpy/intermediate/love-distance/

You’re a relationship scientist, and you’ve developed a questionnaire that determines a person’s love score - a real-valued number between 0 and 100. Your theory is that two people with similar love scores should make a good match 👩‍❤️‍💋‍👨

Given the love scores for 10 different people, create a 2-d array where (i,j) gives the absolute difference of the love scores for person i and person j.



In [1]:
import numpy as np
generator = np.random.default_rng(1010)
love_scores = np.round(generator.uniform(low=0, high=100, size=10), 2)

print(love_scores)
# [ 9.5  53.58 91.77 98.15 84.88 74.61 40.94 56.49  8.39 64.69]

[ 9.5  53.58 91.77 98.15 84.88 74.61 40.94 56.49  8.39 64.69]


## Solution 1

In [2]:
np.abs(love_scores[:, None] - love_scores[None, :])

array([[ 0.  , 44.08, 82.27, 88.65, 75.38, 65.11, 31.44, 46.99,  1.11,
        55.19],
       [44.08,  0.  , 38.19, 44.57, 31.3 , 21.03, 12.64,  2.91, 45.19,
        11.11],
       [82.27, 38.19,  0.  ,  6.38,  6.89, 17.16, 50.83, 35.28, 83.38,
        27.08],
       [88.65, 44.57,  6.38,  0.  , 13.27, 23.54, 57.21, 41.66, 89.76,
        33.46],
       [75.38, 31.3 ,  6.89, 13.27,  0.  , 10.27, 43.94, 28.39, 76.49,
        20.19],
       [65.11, 21.03, 17.16, 23.54, 10.27,  0.  , 33.67, 18.12, 66.22,
         9.92],
       [31.44, 12.64, 50.83, 57.21, 43.94, 33.67,  0.  , 15.55, 32.55,
        23.75],
       [46.99,  2.91, 35.28, 41.66, 28.39, 18.12, 15.55,  0.  , 48.1 ,
         8.2 ],
       [ 1.11, 45.19, 83.38, 89.76, 76.49, 66.22, 32.55, 48.1 ,  0.  ,
        56.3 ],
       [55.19, 11.11, 27.08, 33.46, 20.19,  9.92, 23.75,  8.2 , 56.3 ,
         0.  ]])

## Solution 2

In [3]:
np.abs(np.subtract.outer(love_scores, love_scores))

array([[ 0.  , 44.08, 82.27, 88.65, 75.38, 65.11, 31.44, 46.99,  1.11,
        55.19],
       [44.08,  0.  , 38.19, 44.57, 31.3 , 21.03, 12.64,  2.91, 45.19,
        11.11],
       [82.27, 38.19,  0.  ,  6.38,  6.89, 17.16, 50.83, 35.28, 83.38,
        27.08],
       [88.65, 44.57,  6.38,  0.  , 13.27, 23.54, 57.21, 41.66, 89.76,
        33.46],
       [75.38, 31.3 ,  6.89, 13.27,  0.  , 10.27, 43.94, 28.39, 76.49,
        20.19],
       [65.11, 21.03, 17.16, 23.54, 10.27,  0.  , 33.67, 18.12, 66.22,
         9.92],
       [31.44, 12.64, 50.83, 57.21, 43.94, 33.67,  0.  , 15.55, 32.55,
        23.75],
       [46.99,  2.91, 35.28, 41.66, 28.39, 18.12, 15.55,  0.  , 48.1 ,
         8.2 ],
       [ 1.11, 45.19, 83.38, 89.76, 76.49, 66.22, 32.55, 48.1 ,  0.  ,
        56.3 ],
       [55.19, 11.11, 27.08, 33.46, 20.19,  9.92, 23.75,  8.2 , 56.3 ,
         0.  ]])

# Q2 - Professor Prick Problem

https://www.practiceprobs.com/problemsets/python-numpy/intermediate/professor-prick/

You’re a vindictive professor 👨‍🏫 and one of your pet peeves is when students rush through their exams. To teach them a lesson, you decide to give zeros to the first three students who score less than sixty, in the order they turned in their exams.

Given a 1-d array of integers, identify the first three values less than sixty and replace them with zero.



In [4]:
import numpy as np
generator = np.random.default_rng(80085)
scores = np.round(generator.uniform(low=30, high=100, size=15))

print(scores)

[68. 36. 76. 57. 56. 54. 63. 64. 36. 88. 80. 82. 84. 76. 42.]


## Solution 1

In [5]:
scores[(scores < 60).nonzero()[0][:3]] = 0
scores

array([68.,  0., 76.,  0.,  0., 54., 63., 64., 36., 88., 80., 82., 84.,
       76., 42.])

## Solution 2

In [6]:
indices = np.where(scores < 60)[0][:3]
scores[indices] = 0
scores

array([68.,  0., 76.,  0.,  0., 54., 63., 64., 36., 88., 80., 82., 84.,
       76., 42.])

# Q3 - Pyscho Parent Problem

https://www.practiceprobs.com/problemsets/python-numpy/intermediate/psycho-parent/

Eager to make your mark on the PTA, you decide the best way to hide eggs for the upcoming Easter egg hunt is to use NumPy . You represent the field as a 10x10 array of 0s.

In [7]:
field = np.zeros(shape = (10, 10))

print(field)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Insert 20 random normal values at random (non repeating) locations in the grid. Then you'll know how much candy to hide at each spot.

## Solution 1

In [8]:
generator = np.random.default_rng(1234)
vals = np.round(generator.normal(size=20), 2)
locs = generator.choice(field.size, len(vals), replace=False)
field.ravel()[locs] = vals
field

array([[ 0.52,  0.  ,  0.  , -1.48,  0.  ,  2.91,  0.  ,  0.  ,  0.  ,
         0.  ],
       [ 0.  , -1.27,  0.  ,  0.  ,  0.  , -1.6 ,  0.  ,  1.73,  0.  ,
         0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.43,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.34,  0.  ,  0.  ,  0.  ,
        -1.67],
       [ 0.  ,  0.86,  0.74,  0.  ,  0.  ,  0.  ,  1.32,  0.  ,  0.52,
         0.  ],
       [ 0.  , -1.  ,  0.  ,  0.  ,  0.  ,  0.15,  0.  ,  0.  ,  0.  ,
         0.  ],
       [ 0.  , -0.51,  0.  , -0.86,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , -2.16,  0.  ,  0.95,  0.  ,  0.  ,
         0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.06]])

## Solution 2

In [9]:
indices = np.random.choice(range(100), size=20, replace=False)
values = np.random.normal(size=20)

field.flat[indices] = values
field

array([[ 0.52      ,  0.34819774,  0.1341654 , -0.56778677,  0.        ,
         2.91      ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        , -1.27      ,  0.        ,  0.        , -1.55871944,
        -1.6       ,  0.        , -0.38805689,  0.        ,  0.        ],
       [ 0.39250666,  0.        ,  0.        ,  1.06543295,  0.43      ,
         0.        ,  0.2028482 ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        , -1.07190126,  0.        ,  1.58498953,
         0.34      ,  0.        ,  0.        ,  0.        , -1.67      ],
       [ 0.        ,  0.86      ,  0.74      ,  0.        ,  0.70079269,
        -0.10265137,  1.32      ,  0.        ,  0.52      ,  0.        ],
       [ 0.        , -1.        ,  0.        , -0.76073307,  0.        ,
         0.15      ,  0.35603928,  0.        ,  0.        , -0.78384107],
       [ 0.        , -0.51      ,  0.        , -0.86      ,  0.        ,
         0.        ,  0.        ,  0.        