<a href="https://www.kaggle.com/code/matinmahmoudi/numpy-fun-problems-advanced?scriptVersionId=216093448" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# My Solutions for Numpy Fun Problems - Advanced

Welcome to my  solutions for the "Advanced" level Numpy practice problems. These problems represent the pinnacle of complexity and are designed to challenge and refine your Numpy skills. You can access these advanced problems at:

- [Practice Problems Source](https://www.practiceprobs.com/problemsets/python-numpy/advanced/)

If you have diligently worked through the previous levels and are now tackling these advanced challenges, you're on the right path to mastering Numpy. For those who might have missed or wish to review the "Proficient" level problems, you can find my solutions here:

- [Previous Notebook: Numpy Fun Problems - Proficient](https://www.kaggle.com/code/matinmahmoodi/numpy-fun-problems-proficient)

Engagement and diverse perspectives enhance the learning experience for everyone. Therefore, I warmly invite you to share any alternative solutions, insights, or feedback in the comments section. Let's learn and grow together!

### **Your support through upvotes is greatly appreciated if you find this notebook insightful and helpful!**


# Q1 - Population Verification Problem

https://www.practiceprobs.com/problemsets/python-numpy/advanced/population-verification/

You manage a local department for the Census responsible for measuring the population of each block in your city . Even though you could do it yourself, for each of the last five years, you’ve tasked this job to your subordinate, Jim.

Each year, Jim gives you a 2x4 array of his population estimates where each element of the array represents a city block. After five years, you have a 5x2x4 array of population estimates called jim where (i,j,k) represents Jim’s population estimate for block (j,k) of year i.



In [1]:
import numpy as np

generator = np.random.default_rng(2357)
jim = np.round(generator.normal(loc=100, scale=5, size=(5,2,4)))

print(jim)

[[[106. 103.  92. 100.]
  [ 94. 102.  94. 100.]]

 [[104.  96. 109.  96.]
  [101. 104. 102.  92.]]

 [[102. 102. 108. 101.]
  [ 91. 101. 106.  99.]]

 [[101.  98.  95. 102.]
  [100. 101.  99.  93.]]

 [[107. 101. 104. 105.]
  [102.  97. 101. 102.]]]


You don’t fully trust Jim’s estimates because you see him spending an ungodly amount of time on Facebook. So, each year, you go behind his back and measure the population of two city blocks. After five years, you have the following data:

blocks, a 5x2x2 array indicating which blocks you measured each year where (i,j) gives the coordinates for the jth block you measured in year i

pops, a corresponding 5x2 array where (i,j) gives the population you measured for the jth block in year i

In [2]:
blocks = np.array([
    [[0,2],[1,3]],
    [[1,2],[0,0]],
    [[0,0],[1,2]],
    [[1,1],[0,3]],
    [[0,1],[1,0]]
])

pops = np.array([
    [100, 105],
    [110, 92],
    [95, 99],
    [89, 107],
    [101, 98]
])


How many times was Jim’s estimate at least 10% higher or lower than your estimate?


## Solution

In [3]:
# Index Jim's estimates using the blocks array
jim_estimates = jim[np.arange(5)[:, None], blocks[:, :, 0], blocks[:, :, 1]]

In [4]:
# Calculate the absolute percentage difference between Jim's estimate and your estimate
diff = np.abs(jim_estimates - pops) / pops

In [5]:
# Count the number of times the absolute percentage difference is greater than or equal to 10%
count = np.sum(diff >= 0.1)

In [6]:
count

2

# Q2 - Prime Locations Problem

https://www.practiceprobs.com/problemsets/python-numpy/advanced/prime-locations/

Given a 10x10x10 array of zeros, set (i,j,k) = 1 if i is odd, j is even, and k is prime.

In other words, set these elements to 1: (1,0,2), (1,0,3), (1,0,5), (1,0,7), (1,2,2), ...

In [7]:
import numpy as np

chewy = np.zeros((10,10,10))

print(chewy)

[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0

## Solution 1

In [8]:
# Define a function to check if a number is prime
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

# Set the elements of chewy to 1 if i is odd, j is even, and k is prime
for i in range(10):
    for j in range(10):
        for k in range(10):
            if i % 2 == 1 and j % 2 == 0 and is_prime(k):
                chewy[i, j, k] = 1

chewy

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 1., 1., 0., 1., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 1., 0., 1., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 1., 0., 1., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 1., 0., 1., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 1., 0., 1., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]

## Solution 2 - more professional

In [9]:
i = np.array([1,3,5,7,9])
j = np.array([0,2,4,6,8])
k = np.array([2,3,5,7])
chewy[i[:, None, None], j[None, :, None], k[None, None, :]] = 1

chewy

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 1., 1., 0., 1., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 1., 0., 1., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 1., 0., 1., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 1., 0., 1., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 1., 0., 1., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]

# Q3 - The Game Of Doors Problem

https://www.practiceprobs.com/problemsets/python-numpy/advanced/the-game-of-doors/

You’re preparing for a game show where you play the following game.

You’re faced with four doors    
Behind one door is cash money 🤑
Behind the other three doors is steaming pile of broccoli 🥦

If you pick the door with money, you get the option to play again at the risk of losing the money you’ve collected thus far. If you keep winning, you can play a maximum of three rounds before the game show host kicks you off his show.

You have some strategy ideas you’d like to evaluate before you go on the show. You hire an unpaid intern to scour through historic recordings of the show and log data on where prizes were located and the value of each prize.

Your intern gets back to you with the following matrices:

prize_doors: Here, element (i,j) identifies the door hiding the prize in the ith game of round j
prizes: Here (i, j) gives the prize amount in the ith game of round j


In [10]:
import numpy as np

prize_doors = np.array([
    [1, 0, 2],
    [0, 0, 1],
    [3, 3, 1],
    [1, 2, 0],
    [2, 1, 1]
])

prizes = np.array([
    [100, 150, 500],
    [200, 300, 250],
    [150, 100, 325],
    [425, 200, 100],
    [200, 250, 300]
])

Build a 5x3x4 matrix where (i,j,k) represents the prize behind door k of round j of game i.



## Solution 1

In [11]:
prize_matrix = np.zeros((5, 3, 4))

for i in range(5):
    for j in range(3):
        for k in range(4):
            door = prize_doors[i, j]
            prize = prizes[i, j]
            if door == k:
                prize_matrix[i, j, k] = prize

prize_matrix

array([[[  0., 100.,   0.,   0.],
        [150.,   0.,   0.,   0.],
        [  0.,   0., 500.,   0.]],

       [[200.,   0.,   0.,   0.],
        [300.,   0.,   0.,   0.],
        [  0., 250.,   0.,   0.]],

       [[  0.,   0.,   0., 150.],
        [  0.,   0.,   0., 100.],
        [  0., 325.,   0.,   0.]],

       [[  0., 425.,   0.,   0.],
        [  0.,   0., 200.,   0.],
        [100.,   0.,   0.,   0.]],

       [[  0.,   0., 200.,   0.],
        [  0., 250.,   0.,   0.],
        [  0., 300.,   0.,   0.]]])

## Solution 2 - more professional

In [12]:
answer = np.zeros((5, 3, 4))
answer[np.arange(5)[:, None], np.arange(3)[None, :], prize_doors] = prizes

answer

array([[[  0., 100.,   0.,   0.],
        [150.,   0.,   0.,   0.],
        [  0.,   0., 500.,   0.]],

       [[200.,   0.,   0.,   0.],
        [300.,   0.,   0.,   0.],
        [  0., 250.,   0.,   0.]],

       [[  0.,   0.,   0., 150.],
        [  0.,   0.,   0., 100.],
        [  0., 325.,   0.,   0.]],

       [[  0., 425.,   0.,   0.],
        [  0.,   0., 200.,   0.],
        [100.,   0.,   0.,   0.]],

       [[  0.,   0., 200.,   0.],
        [  0., 250.,   0.,   0.],
        [  0., 300.,   0.,   0.]]])

# Q4 - Peanut Butter Problem

https://www.practiceprobs.com/problemsets/python-numpy/advanced/peanut-butter/

Given peanut, a 4x5 array of 0s, and butter, a 5-element 1-d array of indices, fill the rows of peanut with 1s starting from the column indices given by butter.


In [13]:
import numpy as np

peanut = np.zeros(shape = (4, 5))
butter = np.array([3, 0, 4, 1])

print(peanut)
print(butter)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[3 0 4 1]


## Solution 1 

In [14]:
for i, index in enumerate(butter):
    peanut[i, index:] = 1
peanut

array([[0., 0., 0., 1., 1.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1.],
       [0., 1., 1., 1., 1.]])

## Solution 2

In [15]:
butter[:, None]

array([[3],
       [0],
       [4],
       [1]])

In [16]:
np.arange(peanut.shape[1])

array([0, 1, 2, 3, 4])

In [17]:
butter[:, None] <= np.arange(peanut.shape[1])

array([[False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [False, False, False, False,  True],
       [False,  True,  True,  True,  True]])

In [18]:
(butter[:, None] <= np.arange(peanut.shape[1])).astype('float64')

array([[0., 0., 0., 1., 1.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1.],
       [0., 1., 1., 1., 1.]])

# Q5 - Freckle Problem

https://www.practiceprobs.com/problemsets/python-numpy/advanced/freckle/

Given a 1-D array called freckle,

In [19]:
import numpy as np
freckle = np.array([2,7,3,1,0,5])

perform the following sequence of operations.
1. Sort the elements in descending order	7, 5, 3, 2, 1, 0
2. Take their cumulative sum	7, 12, 15, 17, 18, 18
3. Undo the sort from step 1	17, 7, 15, 18, 18, 12

## Solution

In [20]:
# sort descending
sorted_idxs = np.argsort(freckle)[::-1]
freckle_descending = freckle[sorted_idxs]
freckle_descending

array([7, 5, 3, 2, 1, 0])

In [21]:
# cumulative sum
freckle_cumsum = np.cumsum(freckle_descending)
freckle_cumsum

array([ 7, 12, 15, 17, 18, 18])

In [22]:
# undo sort
undo_sorted_idxs = np.argsort(sorted_idxs)
result = freckle_cumsum[undo_sorted_idxs]
result

array([17,  7, 15, 18, 18, 12])

# Q6 - Get Rich Bot Problem

https://www.practiceprobs.com/problemsets/python-numpy/advanced/get-rich-bot/

You've developed an algorithmic stock trading bot to strike it rich 🤑, but you want to backtest it before putting it into production. You have price data on 10 stocks, each tracked at 8 regular time intervals.


In [23]:
import numpy as np

rng = np.random.default_rng(1234)
prices = [rng.normal(rng.lognormal(3, 1), size=8).round(2) for i in range(10)]
prices = np.vstack(prices)

print(prices)

[[  4.1    4.78   4.19   4.9    6.95   2.56   4.99   2.37]
 [ 27.81  29.65  27.46  28.84  27.06  26.17  28.76  30.06]
 [ 32.79  34.06  34.56  34.98  32.63  34.49  34.14  33.76]
 [ 19.67  19.73  21.68  20.61  19.87  17.86  19.48  19.85]
 [  4.24   6.39   5.32   3.87   4.23   5.27   6.68   4.06]
 [ 98.02  96.79  99.02  99.94  98.28  99.15  98.19  98.49]
 [107.11 105.01 109.01 105.19 107.06 106.71 106.13 106.41]
 [ 17.89  16.34  15.88  17.53  18.79  16.91  18.75  16.96]
 [ 96.28  95.84  96.26  94.48  95.42  93.75  93.54  96.24]
 [ 18.31  17.43  16.53  20.2   18.68  17.48  17.33  18.96]]


For each stock, your algorithm suggests the best time to buy the stock and the best time to sell the stock.

In [24]:
trade_idxs = [np.sort(rng.choice(8, size=2, replace=False)) for i in range(10)]
trade_idxs = np.vstack(trade_idxs)

print(trade_idxs)

[[0 1]
 [3 6]
 [2 4]
 [1 5]
 [0 3]
 [2 7]
 [2 3]
 [1 3]
 [3 6]
 [1 4]]


trade_idxs identifies the index of the buy price and sell price for each stock. So, the holding periods look like this.



In [25]:
"""
| trade_idxs |     0 |     1 |     2 |      3 |     4 |     5 |     6 |     7 |
|:-----------|------:|------:|------:|-------:|------:|------:|------:|------:|
| [0 1]      |  4.1  |  4.78 | ----- |  ----- | ----- | ----- | ----- | ----- |
| [3 6]      | ----- | ----- | ----- |  28.84 | 27.06 | 26.17 | 28.76 | ----- |
| [2 4]      | ----- | ----- | 34.56 |  34.98 | 32.63 | ----- | ----- | ----- |
| [1 5]      | ----- | 19.73 | 21.68 |  20.61 | 19.87 | 17.86 | ----- | ----- |
| [0 3]      |  4.24 |  6.39 |  5.32 |   3.87 | ----- | ----- | ----- | ----- |
| [2 7]      | ----- | ----- | 99.02 |  99.94 | 98.28 | 99.15 | 98.19 | 98.49 |
| [2 3]      | ----- | ----- | 09.01 | 105.19 | ----- | ----- | ----- | ----- |
| [1 3]      | ----- | 16.34 | 15.88 |  17.53 | ----- | ----- | ----- | ----- |
| [3 6]      | ----- | ----- | ----- |  94.48 | 95.42 | 93.75 | 93.54 | ----- |
| [1 4]      | ----- | 17.43 | 16.53 |  20.2  | 18.68 | ----- | ----- | ----- |
"""

'\n| trade_idxs |     0 |     1 |     2 |      3 |     4 |     5 |     6 |     7 |\n|:-----------|------:|------:|------:|-------:|------:|------:|------:|------:|\n| [0 1]      |  4.1  |  4.78 | ----- |  ----- | ----- | ----- | ----- | ----- |\n| [3 6]      | ----- | ----- | ----- |  28.84 | 27.06 | 26.17 | 28.76 | ----- |\n| [2 4]      | ----- | ----- | 34.56 |  34.98 | 32.63 | ----- | ----- | ----- |\n| [1 5]      | ----- | 19.73 | 21.68 |  20.61 | 19.87 | 17.86 | ----- | ----- |\n| [0 3]      |  4.24 |  6.39 |  5.32 |   3.87 | ----- | ----- | ----- | ----- |\n| [2 7]      | ----- | ----- | 99.02 |  99.94 | 98.28 | 99.15 | 98.19 | 98.49 |\n| [2 3]      | ----- | ----- | 09.01 | 105.19 | ----- | ----- | ----- | ----- |\n| [1 3]      | ----- | 16.34 | 15.88 |  17.53 | ----- | ----- | ----- | ----- |\n| [3 6]      | ----- | ----- | ----- |  94.48 | 95.42 | 93.75 | 93.54 | ----- |\n| [1 4]      | ----- | 17.43 | 16.53 |  20.2  | 18.68 | ----- | ----- | ----- |\n'

Given prices and trade_idxs, calculate the average price of each holding period.

## Solution 1

In [26]:
average_prices = np.array([prices[i, trade_idxs[i, 0]:trade_idxs[i, 1]+1].mean() for i in range(prices.shape[0])])
average_prices

array([  4.44      ,  27.7075    ,  34.05666667,  19.95      ,
         4.955     ,  98.845     , 107.1       ,  16.58333333,
        94.2975    ,  18.21      ])

## Solution 2

In [27]:
# Identify which elements to "mask"
col_idxs = np.arange(prices.shape[1])
mask = (col_idxs < trade_idxs[:, [0]]) | (col_idxs > trade_idxs[:, [1]])

In [28]:
# convert mask elements to nan
prices[mask] = np.nan

In [29]:
# Calculate the row means
np.nanmean(prices, axis=1)

array([  4.44      ,  27.7075    ,  34.05666667,  19.95      ,
         4.955     ,  98.845     , 107.1       ,  16.58333333,
        94.2975    ,  18.21      ])